#!/bin/bash

PATH=$PATH:/etc/randomVPN

# Import variables from the settings file
source ./settings

# If no arguments were passed throw error
if [ $# -eq 0 ]
then
	./log.sh "NoArg"
# Starts tunnel if -s was passed in
elif [ $1 = "-s" ]
then
	if ifconfig | grep "tun" &> /dev/null
	then
		./log.sh "TunnelOpen_Error"
	else
	        ./connectTunnel.sh
	fi
# Used for the crontab features
elif [ $1 = "-c" ]
then
	# Checks for the reboot argument passed 
	if [ $2 = "-r" ]
	then
		#checks to see if we are allowed to reboot the system
		if [ $systemreboot =  true ]
		then
			hour="$(date | sed 's/:/ /g' | awk '{ print $4 }')"
			minute="$(date | sed 's/:/ /g' | awk '{ print $5 }')"

			echo "$hour $minute"
			#If reboot is allowed then check for the reboot time
			if [ $restarttime = "$hour:$minute" ]
			then
				./log.sh "Reboot"
				sudo reboot
			fi
		fi
	#Used on reboot for crontab to start the VPN
	elif [ $2 = "-s" ]
	then
		#Checks if start at reboot is active
		if [ $startatreboot = true ]
		then
			./connectTunnel.sh
		fi
	fi
elif [ $1 = "-l" ]
then
        sudo ./showlogs.sh
fi
