#!/bin/bash

PATH=/etc/randomVPN
CONFIG="$(ls . |sort -R |head -n 1)"

if ifconfig | grep "tun"
then
  ./errorLog "TunnelOpen"
else
  if [ $CONFIG = "" ]
  then
    ./errorLog "NoConfig"
  else
    ./connectTunnel $CONFIG
  fi
fi
