#!/bin/bash

PATH=$PATH:/etc/randomVPN

if [[ $# -eq 0 ]]
then
	if ifconfig | grep "tun" &> /dev/null
	then
		./errorlog.sh "TunnelOpen"
	else
	        ./connectTunnel.sh
	fi
elif [[ $1 = "-l" ]]
then
        sudo ./showlogs.sh
fi
